"""Provider catalog refresh — Capstone M2/M3 (PROVIDER_ADAPTER_SPEC.md §2.3).

Live adapters: OpenRouter (public catalog, pricing metadata maps to tiers) and
OpenAI (key-required model list; capability metadata comes from a static family
table because the API exposes none).

Refreshed entries are written to registry/models.<provider>.generated.yaml —
never into the hand-edited models.yaml. Manual entries win on key collision;
deleting the generated file reverts to the manual registry.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from datetime import date
from pathlib import Path

import yaml
from pydantic import ValidationError

from .schema import Ability, LatencyTier, ModelEntry, PricingTier

OPENROUTER_MODELS_URL = "https://openrouter.ai/api/v1/models"
OPENAI_MODELS_URL = "https://api.openai.com/v1/models"
GENERATED_SUFFIX = ".generated.yaml"

_TIMEOUT_SECONDS = 20

# USD per prompt token -> pricing tier ($/1M: 0 | <1 | <5 | <15 | rest)
_TIER_THRESHOLDS = (
    (0.0, PricingTier.free),
    (1e-6, PricingTier.low),
    (5e-6, PricingTier.medium),
    (1.5e-5, PricingTier.high),
)

# ponytail: ability derived from pricing tier alone — real scores need benchmarks (M3+)
_ABILITY_BY_TIER = {
    PricingTier.free: 5,
    PricingTier.low: 6,
    PricingTier.medium: 7,
    PricingTier.high: 8,
    PricingTier.frontier: 9,
}


class RefreshError(Exception):
    """Raised on network/response failures — CLI maps this to exit code 1."""


def _http_get_json(url: str, api_key: str | None) -> dict:
    """GET url, return parsed JSON. The key goes into the header only — never logged."""
    # Only real network schemes — blocks a malicious/typo'd registry URL from
    # reaching file://, ftp:// or custom handlers (SSRF / local-file read).
    scheme = urllib.parse.urlparse(url).scheme.lower()
    if scheme not in ("http", "https"):
        raise RefreshError(f"refusing non-http(s) catalog URL scheme '{scheme}': {url}")
    req = urllib.request.Request(url, headers={"User-Agent": "agentrouter-os"})
    if api_key:
        req.add_header("Authorization", f"Bearer {api_key}")
    try:
        with urllib.request.urlopen(req, timeout=_TIMEOUT_SECONDS) as resp:  # nosec B310 - scheme checked above
            body = resp.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        raise RefreshError(f"provider returned HTTP {e.code} for {url}") from e
    except urllib.error.URLError as e:
        raise RefreshError(f"network error reaching {url}: {e.reason}") from e
    except TimeoutError as e:
        raise RefreshError(f"timed out after {_TIMEOUT_SECONDS}s reaching {url}") from e
    try:
        return json.loads(body)
    except json.JSONDecodeError as e:
        raise RefreshError(f"provider response is not valid JSON ({e})") from e


def _pricing_tier(prompt_price: float) -> PricingTier:
    for threshold, tier in _TIER_THRESHOLDS:
        if prompt_price <= threshold:
            return tier
    return PricingTier.frontier


def map_openrouter_model(raw: dict) -> ModelEntry:
    """Translate one OpenRouter catalog entry into the neutral registry schema.

    Raises RefreshError if required fields are missing/invalid (fail loud, spec §1).
    """
    model_id = raw.get("id")
    context = raw.get("context_length")
    if not model_id or not isinstance(context, int) or context <= 0:
        raise RefreshError(f"entry missing id/context_length: {raw.get('id', raw)!r}")
    try:
        prompt_price = float((raw.get("pricing") or {}).get("prompt", 0))
    except (TypeError, ValueError) as e:
        raise RefreshError(f"entry '{model_id}': unparseable pricing: {e}") from e
    tier = _pricing_tier(prompt_price)
    score = _ABILITY_BY_TIER[tier]

    supported = raw.get("supported_parameters") or []
    tools = ["tool-use", "function-calling"] if "tools" in supported else []
    modalities = (raw.get("architecture") or {}).get("input_modalities") or []
    max_out = (raw.get("top_provider") or {}).get("max_completion_tokens")

    try:
        return ModelEntry(
            provider="openrouter",
            model_id=model_id,
            display_name=raw.get("name"),
            context_window=context,
            max_output_tokens=max_out
            if isinstance(max_out, int) and max_out > 0
            else max(context // 4, 1024),
            pricing_tier=tier,
            latency_tier=LatencyTier.medium,  # API exposes no latency data
            ability=Ability(coding=score, reasoning=score, writing=score),
            tool_support=tools,
            vision_support="image" in modalities,
            deprecation_status="active",
            notes="auto-generated by providers refresh; ability scores are a "
            "pricing-based heuristic, not benchmarks",
            source="refresh",
            last_updated=date.today(),
        )
    except ValidationError as e:
        raise RefreshError(f"entry '{model_id}' does not fit the registry schema: {e}") from e


def fetch_openrouter_models(
    api_key: str | None, limit: int, match: str | None = None
) -> tuple[list[ModelEntry], list[str]]:
    """Fetch the live OpenRouter catalog. Returns (entries, skipped-entry warnings)."""
    payload = _http_get_json(OPENROUTER_MODELS_URL, api_key)
    data = payload.get("data") if isinstance(payload, dict) else None
    if not isinstance(data, list) or not data:
        raise RefreshError(
            "unexpected response shape from OpenRouter: expected a non-empty 'data' list"
        )
    entries, warnings = [], []
    for raw in data:  # ponytail: API order (newest first); no ranking data to sort by
        if len(entries) >= limit:
            break
        if match and match not in str(raw.get("id", "")):
            continue
        try:
            entries.append(map_openrouter_model(raw))
        except RefreshError as e:
            warnings.append(f"skipped: {e}")
    if not entries:
        raise RefreshError(_no_entries_msg("OpenRouter", match))
    return entries, warnings


# --- OpenAI adapter (M3) ---------------------------------------------------------
#
# GET /v1/models returns only {id, created, owned_by} — no context window, no
# pricing, no capabilities. Capability metadata therefore comes from a static
# family table (longest-prefix match); catalog entries with no family mapping
# (embeddings, audio, images, unknown/new families) are skipped with one
# aggregate warning. The live call still earns its keep: it tells you which
# models YOUR key can actually see, and new snapshots of known families map
# automatically.

# prefix -> (context_window, max_output_tokens, pricing_tier,
#            (coding, reasoning, writing), tools, vision)
_OPENAI_FAMILIES: dict[str, tuple[int, int, PricingTier, tuple[int, int, int], bool, bool]] = {
    "gpt-4o-mini": (128_000, 16_384, PricingTier.low, (7, 6, 7), True, True),
    "gpt-4o": (128_000, 16_384, PricingTier.medium, (8, 7, 8), True, True),
    "gpt-4.1-nano": (1_000_000, 32_768, PricingTier.low, (7, 6, 7), True, True),
    "gpt-4.1-mini": (1_000_000, 32_768, PricingTier.low, (8, 7, 7), True, True),
    "gpt-4.1": (1_000_000, 32_768, PricingTier.medium, (8, 8, 8), True, True),
    "gpt-5-mini": (400_000, 128_000, PricingTier.low, (8, 8, 7), True, True),
    "gpt-5-nano": (400_000, 128_000, PricingTier.low, (7, 7, 7), True, True),
    "gpt-5": (400_000, 128_000, PricingTier.high, (9, 9, 8), True, True),
    "o3-mini": (200_000, 100_000, PricingTier.medium, (8, 8, 6), True, False),
    "o3": (200_000, 100_000, PricingTier.high, (9, 9, 7), True, True),
    "o4-mini": (200_000, 100_000, PricingTier.medium, (8, 8, 7), True, True),
}


def _openai_family(model_id: str) -> tuple | None:
    best = None
    for prefix, meta in _OPENAI_FAMILIES.items():
        if model_id == prefix or model_id.startswith(prefix + "-"):
            if best is None or len(prefix) > len(best[0]):
                best = (prefix, meta)
    return best[1] if best else None


def map_openai_model(raw: dict) -> ModelEntry:
    """Translate one OpenAI /v1/models entry via the static family table.

    Raises RefreshError when the id has no family mapping (caller aggregates these).
    """
    model_id = raw.get("id")
    if not model_id or not isinstance(model_id, str):
        raise RefreshError(f"entry missing id: {raw!r}")
    meta = _openai_family(model_id)
    if meta is None:
        raise RefreshError(f"no family mapping for '{model_id}'")
    context, max_out, tier, (coding, reasoning, writing), tools, vision = meta
    return ModelEntry(
        provider="openai",
        model_id=model_id,
        context_window=context,
        max_output_tokens=max_out,
        pricing_tier=tier,
        latency_tier=LatencyTier.medium,  # API exposes no latency data
        ability=Ability(coding=coding, reasoning=reasoning, writing=writing),
        tool_support=["tool-use", "function-calling"] if tools else [],
        vision_support=vision,
        deprecation_status="active",
        notes="auto-generated by providers refresh; metadata from a static "
        "family table, not benchmarks",
        source="refresh",
        last_updated=date.today(),
    )


def fetch_openai_models(
    api_key: str | None, limit: int, match: str | None = None
) -> tuple[list[ModelEntry], list[str]]:
    """Fetch the models visible to this OPENAI_API_KEY. Returns (entries, warnings)."""
    if not api_key:
        raise RefreshError(
            "OpenAI refresh requires OPENAI_API_KEY (a read-only key is enough); "
            "set it in your environment and retry"
        )
    payload = _http_get_json(OPENAI_MODELS_URL, api_key)
    data = payload.get("data") if isinstance(payload, dict) else None
    if not isinstance(data, list) or not data:
        raise RefreshError(
            "unexpected response shape from OpenAI: expected a non-empty 'data' list"
        )
    entries, unmapped = [], 0
    for raw in data:
        if len(entries) >= limit:
            break
        if match and match not in str(raw.get("id", "")):
            continue
        try:
            entries.append(map_openai_model(raw))
        except RefreshError:
            unmapped += 1
    warnings = (
        [f"skipped {unmapped} catalog entries with no family mapping (non-chat or unknown)"]
        if unmapped
        else []
    )
    if not entries:
        raise RefreshError(_no_entries_msg("OpenAI", match))
    return entries, warnings


def _no_entries_msg(provider: str, match: str | None) -> str:
    if match:
        return f"no {provider} entry matched '--match {match}'"
    return f"no {provider} entry could be mapped to the registry schema"


# provider -> (fetcher, env var holding its API key)
FETCHERS = {
    "openrouter": (fetch_openrouter_models, "OPENROUTER_API_KEY"),
    "openai": (fetch_openai_models, "OPENAI_API_KEY"),
}
SUPPORTED_PROVIDERS = tuple(FETCHERS)


def write_generated_registry(reg_dir: Path, provider: str, entries: list[ModelEntry]) -> Path:
    """Write refreshed entries to models.<provider>.generated.yaml (idempotent overwrite)."""
    path = reg_dir / f"models.{provider}{GENERATED_SUFFIX}"
    doc = {"models": [e.model_dump(mode="json", exclude_none=True) for e in entries]}
    header = (
        f"# AUTO-GENERATED by `agentrouter providers refresh {provider}` — do not hand-edit.\n"
        f"# Manual models.yaml always wins on collision. Delete this file to revert.\n"
    )
    path.write_text(header + yaml.safe_dump(doc, sort_keys=False), encoding="utf-8")
    return path
