"""Provider catalog refresh — Capstone M2 (PROVIDER_ADAPTER_SPEC.md §2.3).

OpenRouter is the first (and currently only) live adapter: one public endpoint,
aggregated multi-vendor catalog, pricing metadata that maps cleanly to tiers.

Refreshed entries are written to registry/models.<provider>.generated.yaml —
never into the hand-edited models.yaml. Manual entries win on key collision;
deleting the generated file reverts to the manual registry.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from datetime import date
from pathlib import Path

import yaml
from pydantic import ValidationError

from .schema import Ability, LatencyTier, ModelEntry, PricingTier

OPENROUTER_MODELS_URL = "https://openrouter.ai/api/v1/models"
SUPPORTED_PROVIDERS = ("openrouter",)
GENERATED_SUFFIX = ".generated.yaml"

_TIMEOUT_SECONDS = 20

# USD per prompt token -> pricing tier ($/1M: 0 | <1 | <5 | <15 | rest)
_TIER_THRESHOLDS = (
    (0.0, PricingTier.free),
    (1e-6, PricingTier.low),
    (5e-6, PricingTier.medium),
    (1.5e-5, PricingTier.high),
)

# ponytail: ability derived from pricing tier alone — real scores need benchmarks (M3+)
_ABILITY_BY_TIER = {
    PricingTier.free: 5,
    PricingTier.low: 6,
    PricingTier.medium: 7,
    PricingTier.high: 8,
    PricingTier.frontier: 9,
}


class RefreshError(Exception):
    """Raised on network/response failures — CLI maps this to exit code 1."""


def _http_get_json(url: str, api_key: str | None) -> dict:
    """GET url, return parsed JSON. The key goes into the header only — never logged."""
    req = urllib.request.Request(url, headers={"User-Agent": "agentrouter-os"})
    if api_key:
        req.add_header("Authorization", f"Bearer {api_key}")
    try:
        with urllib.request.urlopen(req, timeout=_TIMEOUT_SECONDS) as resp:
            body = resp.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        raise RefreshError(f"provider returned HTTP {e.code} for {url}") from e
    except urllib.error.URLError as e:
        raise RefreshError(f"network error reaching {url}: {e.reason}") from e
    except TimeoutError as e:
        raise RefreshError(f"timed out after {_TIMEOUT_SECONDS}s reaching {url}") from e
    try:
        return json.loads(body)
    except json.JSONDecodeError as e:
        raise RefreshError(f"provider response is not valid JSON ({e})") from e


def _pricing_tier(prompt_price: float) -> PricingTier:
    for threshold, tier in _TIER_THRESHOLDS:
        if prompt_price <= threshold:
            return tier
    return PricingTier.frontier


def map_openrouter_model(raw: dict) -> ModelEntry:
    """Translate one OpenRouter catalog entry into the neutral registry schema.

    Raises RefreshError if required fields are missing/invalid (fail loud, spec §1).
    """
    model_id = raw.get("id")
    context = raw.get("context_length")
    if not model_id or not isinstance(context, int) or context <= 0:
        raise RefreshError(f"entry missing id/context_length: {raw.get('id', raw)!r}")
    try:
        prompt_price = float((raw.get("pricing") or {}).get("prompt", 0))
    except (TypeError, ValueError) as e:
        raise RefreshError(f"entry '{model_id}': unparseable pricing: {e}") from e
    tier = _pricing_tier(prompt_price)
    score = _ABILITY_BY_TIER[tier]

    supported = raw.get("supported_parameters") or []
    tools = ["tool-use", "function-calling"] if "tools" in supported else []
    modalities = (raw.get("architecture") or {}).get("input_modalities") or []
    max_out = (raw.get("top_provider") or {}).get("max_completion_tokens")

    try:
        return ModelEntry(
            provider="openrouter",
            model_id=model_id,
            display_name=raw.get("name"),
            context_window=context,
            max_output_tokens=max_out
            if isinstance(max_out, int) and max_out > 0
            else max(context // 4, 1024),
            pricing_tier=tier,
            latency_tier=LatencyTier.medium,  # API exposes no latency data
            ability=Ability(coding=score, reasoning=score, writing=score),
            tool_support=tools,
            vision_support="image" in modalities,
            deprecation_status="active",
            notes="auto-generated by providers refresh; ability scores are a "
            "pricing-based heuristic, not benchmarks",
            source="refresh",
            last_updated=date.today(),
        )
    except ValidationError as e:
        raise RefreshError(f"entry '{model_id}' does not fit the registry schema: {e}") from e


def fetch_openrouter_models(api_key: str | None, limit: int) -> tuple[list[ModelEntry], list[str]]:
    """Fetch the live OpenRouter catalog. Returns (entries, skipped-entry warnings)."""
    payload = _http_get_json(OPENROUTER_MODELS_URL, api_key)
    data = payload.get("data") if isinstance(payload, dict) else None
    if not isinstance(data, list) or not data:
        raise RefreshError(
            "unexpected response shape from OpenRouter: expected a non-empty 'data' list"
        )
    entries, warnings = [], []
    for raw in data:  # ponytail: API order (newest first); no ranking data to sort by
        if len(entries) >= limit:
            break
        try:
            entries.append(map_openrouter_model(raw))
        except RefreshError as e:
            warnings.append(f"skipped: {e}")
    if not entries:
        raise RefreshError("no OpenRouter entry could be mapped to the registry schema")
    return entries, warnings


def write_generated_registry(reg_dir: Path, provider: str, entries: list[ModelEntry]) -> Path:
    """Write refreshed entries to models.<provider>.generated.yaml (idempotent overwrite)."""
    path = reg_dir / f"models.{provider}{GENERATED_SUFFIX}"
    doc = {"models": [e.model_dump(mode="json", exclude_none=True) for e in entries]}
    header = (
        f"# AUTO-GENERATED by `agentrouter providers refresh {provider}` — do not hand-edit.\n"
        f"# Manual models.yaml always wins on collision. Delete this file to revert.\n"
    )
    path.write_text(header + yaml.safe_dump(doc, sort_keys=False), encoding="utf-8")
    return path
